### ISSUE TITLE
Move heredoc (`<<EOF` ... `EOF`) to different files.

### ISSUE THREAD

**Issue by robertdebock** [robertdebock/terraform-aws-vault#53]
There are some heredoc markers in .tf file. (`cloudwatch.tf`, `iam.tf` and `outputs.tf`) (`grep -Ril EOF *.tf`).

- [x] Verify if using heredoc is preferable over reading files. (`file(...)` or `templatefile(...)`)

If heredoc is not preferred:

- [ ] Identify files with heredoc.
- [ ] Move content in separate files. (`something.json`)
- [ ] Use the `file` or `template file` function to read the file.

**Comment by joe-rua** [comment]
@robertdebock I reviewed this and did find that `cloudwatch.tf` would benefit from leveraging `templatefile` over `file()` or as a heredoc due to the size. 

I did fork this & make the changes, and tested; however, I haven't contributed to a project, so I don't know if you want me to do a PR & then it should link here or how that should be done. Please let me know the best way to submit this so I can send it over for you to review.

**Comment by robertdebock** [comment]
Great work, thanks @joe-rua. CI is testing your change now. We'll spend some time to verify it as well, but your contributions look good.

**Comment by robertdebock** [comment]
## Identify files with heredoc.

- [ ] cloudwatch.tf (1x remaining)
- [ ] iam.tf (1x remaining)
