### ISSUE TITLE
Is it mandatory to have one public subnet in VPC ?

### ISSUE THREAD

**Issue by varun-r-d** [robertdebock/terraform-aws-vault#77]
https://github.com/robertdebock/terraform-aws-vault/blob/0d107a559170b25798caa8c9e61ecabc6b04f27b/network.tf#L49C1-L50C1

**Comment by robertdebock** [comment]
Good question, let's see;

Here is the code you are referring to:

```hcl
data "aws_nat_gateway" "default" {
  count     = var.vault_aws_vpc_id == "" ? 0 : 1
  subnet_id = var.vault_public_subnet_ids[0]
}
```

So; Terraform will find an `aws_nat_gateway`, when `var.vault_aws_vpc_id` is not empty. (`""`).

In other words, when you supply your own VPC, it should have a NAT gateway.

The instances need a NAT gateway in order to download Vault and run OS-updates.

So; to answer your question; Yes, you need a NAT gateway, so implicitly you need a public subnet.

Hope that answers the question a bit, let me know if you need more help.

Regards,

Robert.
